import type { MetadataRoute } from "next";

/**
 * PWA manifest — served at /manifest.webmanifest; Next injects the
 * <link rel="manifest"> automatically.
 *
 * Installability notes: /icon is a real 512×512 PNG generated by
 * src/app/icon.tsx — declared at its true size only (a mismatch between
 * declared and actual dimensions makes Chromium reject installability).
 * The same art is declared once more as maskable so Android's adaptive
 * launcher gets a full-bleed icon; the ₹ glyph sits well inside the
 * maskable safe zone. Keep these routes reachable WITHOUT auth (see
 * src/middleware.ts) — browsers fetch them without cookies.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    scope: "/",
    name: "Family Ledger",
    short_name: "Ledger",
    description: "High-speed expense tracking for the family — bills, lifestyle and one-time buys at a glance.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#09090b",
    theme_color: "#171717",
    categories: ["finance", "productivity"],
    // Android long-press app shortcuts. "Add expense" deep-links with ?new=1,
    // which QuickAddProvider consumes on mount to open the sheet directly.
    shortcuts: [
      {
        name: "Add expense",
        short_name: "Add",
        description: "Log a new expense with Quick Add",
        url: "/?new=1",
      },
      {
        name: "Ledger",
        short_name: "Ledger",
        description: "Browse and edit transactions",
        url: "/transactions",
      },
    ],
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
